name: Build

on:
  push:
    branches:
      - [ main ]
  pull_request:
    branches:
      - [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Compile program
        run: g++ main.cpp --std=c++17 -o tally

      - name: Upload program artifact
        uses: actions/upload-artifact@v7
        with:
          name: tally
          path: tally
